/**
 * Hooks Generator
 *
 * Generates Claude Code hook scripts and hooks.json manifest.
 */

export interface GeneratedHook {
  filename: string;
  content: string;
  executable: boolean;
}

export interface HooksManifest {
  hooks: Record<string, Array<{
    type: string;
    command: string;
    matcher?: string;
  }>>;
}

/**
 * Generate the guard script that prevents hooks from firing outside TasteKit directories.
 */
function generateGuardScript(): GeneratedHook {
  return {
    filename: 'tastekit-guard.sh',
    executable: true,
    content: `#!/usr/bin/env bash
# TasteKit Guard — prevents hooks from firing in non-TasteKit directories.
# Generated by TasteKit. Do not edit manually.

if [ ! -d ".tastekit" ]; then
  exit 0
fi

# TasteKit workspace detected — allow hook to proceed
exit 0
`,
  };
}

/**
 * Generate session-orient hook (SessionStart).
 * Injects workspace state at the start of each session.
 */
function generateSessionOrientScript(): GeneratedHook {
  return {
    filename: 'session-orient.sh',
    executable: true,
    content: `#!/usr/bin/env bash
# TasteKit Session Orient — injects workspace context at session start.
# Generated by TasteKit. Do not edit manually.

# Guard: only run in TasteKit workspaces
if [ ! -d ".tastekit" ]; then
  exit 0
fi

CONTEXT=""

# Show workspace tree (2 levels)
if command -v tree &> /dev/null; then
  TREE=$(tree -L 2 .tastekit --noreport 2>/dev/null)
  if [ -n "$TREE" ]; then
    CONTEXT="Workspace structure:\\n$TREE"
  fi
fi

# Surface pending drift proposals
DRIFT_DIR=".tastekit/ops/drift"
if [ -d "$DRIFT_DIR" ]; then
  DRIFT_COUNT=$(find "$DRIFT_DIR" -name "*.json" 2>/dev/null | wc -l | tr -d ' ')
  if [ "$DRIFT_COUNT" -gt 0 ]; then
    CONTEXT="$CONTEXT\\n\\nPending drift proposals: $DRIFT_COUNT"
  fi
fi

# Count observations and tensions
OBS_DIR=".tastekit/ops/observations"
if [ -d "$OBS_DIR" ]; then
  OBS_COUNT=$(find "$OBS_DIR" -name "*.json" 2>/dev/null | wc -l | tr -d ' ')
  if [ "$OBS_COUNT" -gt 0 ]; then
    CONTEXT="$CONTEXT\\nObservations recorded: $OBS_COUNT"
  fi
fi

if [ -n "$CONTEXT" ]; then
  echo "{\\"additionalContext\\": \\"$CONTEXT\\"}"
fi
`,
  };
}

/**
 * Generate artifact-validate hook (PostToolUse:Write).
 * Validates writes to self/ and knowledge/ directories.
 */
function generateArtifactValidateScript(): GeneratedHook {
  return {
    filename: 'artifact-validate.sh',
    executable: true,
    content: `#!/usr/bin/env bash
# TasteKit Artifact Validate — validates writes to managed directories.
# Generated by TasteKit. Do not edit manually.

if [ ! -d ".tastekit" ]; then
  exit 0
fi

# Read the file path from stdin (Claude Code passes tool input as JSON)
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Check if writing to managed TasteKit directories
case "$FILE_PATH" in
  *.tastekit/self/*)
    # Validate identity artifact writes
    if [[ "$FILE_PATH" == *.json ]]; then
      # Basic JSON validation
      if command -v python3 &> /dev/null; then
        echo "$INPUT" | python3 -c "import json,sys; json.load(sys.stdin)" 2>/dev/null
        if [ $? -ne 0 ]; then
          echo "{\\"additionalContext\\": \\"Warning: Writing invalid JSON to identity directory\\"}"
        fi
      fi
    fi
    ;;
  *.tastekit/knowledge/*)
    # Knowledge directory writes are fine
    ;;
esac

exit 0
`,
  };
}

/**
 * Generate auto-commit hook (PostToolUse:Write, async).
 * Non-blocking git commit after writes.
 */
function generateAutoCommitScript(): GeneratedHook {
  return {
    filename: 'auto-commit.sh',
    executable: true,
    content: `#!/usr/bin/env bash
# TasteKit Auto-Commit — non-blocking git commit after TasteKit file changes.
# Generated by TasteKit. Do not edit manually.

if [ ! -d ".tastekit" ]; then
  exit 0
fi

# Only commit changes within .tastekit/
CHANGES=$(git diff --name-only .tastekit/ 2>/dev/null)
UNTRACKED=$(git ls-files --others --exclude-standard .tastekit/ 2>/dev/null)

if [ -z "$CHANGES" ] && [ -z "$UNTRACKED" ]; then
  exit 0
fi

# Stage and commit TasteKit changes
git add .tastekit/ 2>/dev/null
STAT=$(git diff --cached --stat .tastekit/ 2>/dev/null)
if [ -n "$STAT" ]; then
  git commit -m "tastekit: auto-save workspace changes" --no-verify 2>/dev/null
fi

exit 0
`,
  };
}

/**
 * Generate session-capture hook (Stop).
 * Saves session metadata on session end.
 */
function generateSessionCaptureScript(): GeneratedHook {
  return {
    filename: 'session-capture.sh',
    executable: true,
    content: `#!/usr/bin/env bash
# TasteKit Session Capture — saves session metadata on session end.
# Generated by TasteKit. Do not edit manually.

if [ ! -d ".tastekit" ]; then
  exit 0
fi

SESSIONS_DIR=".tastekit/ops/sessions"
mkdir -p "$SESSIONS_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
FILENAME="$SESSIONS_DIR/$(date -u +"%Y%m%d-%H%M%S").json"

# Capture basic session info
cat > "$FILENAME" << ENDJSON
{
  "ended_at": "$TIMESTAMP",
  "workspace": "$(pwd)",
  "git_branch": "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'none')",
  "git_hash": "$(git rev-parse --short HEAD 2>/dev/null || echo 'none')"
}
ENDJSON

# Stage session file
git add "$FILENAME" 2>/dev/null
git commit -m "tastekit: capture session $TIMESTAMP" --no-verify 2>/dev/null

exit 0
`,
  };
}

/**
 * Generate all hook scripts and the hooks.json manifest.
 */
export function generateHooks(): { scripts: GeneratedHook[]; manifest: HooksManifest } {
  const scripts: GeneratedHook[] = [
    generateGuardScript(),
    generateSessionOrientScript(),
    generateArtifactValidateScript(),
    generateAutoCommitScript(),
    generateSessionCaptureScript(),
  ];

  const manifest: HooksManifest = {
    hooks: {
      SessionStart: [
        { type: 'command', command: '.tastekit/hooks/session-orient.sh' },
      ],
      PostToolUse: [
        { type: 'command', command: '.tastekit/hooks/artifact-validate.sh', matcher: 'Write' },
        { type: 'command', command: '.tastekit/hooks/auto-commit.sh', matcher: 'Write' },
      ],
      Stop: [
        { type: 'command', command: '.tastekit/hooks/session-capture.sh' },
      ],
    },
  };

  return { scripts, manifest };
}
