import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const ADAPTERS: Record<string, string> = {
  'claude-code': 'Claude Code',
  'manus': 'Manus',
  'openclaw': 'OpenClaw',
  'autopilots': 'Autopilots',
};

export const exportCommand = new Command('export')
  .description('Export to runtime adapter format')
  .option('--target <adapter>', 'Target adapter: claude-code, manus, openclaw, autopilots, agents-md')
  .option('--out <dir>', 'Output directory', './export')
  .action(async (options) => {
    if (!options.target) {
      console.error(chalk.red('Please specify a target adapter with --target'));
      console.log(chalk.gray('Available targets: claude-code, manus, openclaw, autopilots, agents-md'));
      process.exit(1);
    }

    const workspacePath = process.cwd();
    const tastekitDir = join(workspacePath, '.tastekit');

    if (!existsSync(tastekitDir)) {
      console.error(chalk.red('No .tastekit directory found. Run `tastekit init` first.'));
      process.exit(1);
    }

    const constitutionPath = join(tastekitDir, 'artifacts', 'constitution.v1.json');
    if (!existsSync(constitutionPath)) {
      console.error(chalk.red('No compiled artifacts found. Run `tastekit compile` first.'));
      process.exit(1);
    }

    // Handle AGENTS.md export as a special case
    if (options.target === 'agents-md') {
      const spinner = ora('Generating AGENTS.md from TasteKit artifacts...').start();
      try {
        const constitution = JSON.parse(readFileSync(constitutionPath, 'utf-8'));
        const agentsMd = generateAgentsMd(constitution, tastekitDir);
        const outPath = join(options.out === './export' ? workspacePath : options.out, 'AGENTS.md');
        mkdirSync(join(outPath, '..'), { recursive: true });
        writeFileSync(outPath, agentsMd, 'utf-8');
        spinner.succeed(chalk.green(`AGENTS.md exported to ${outPath}`));
      } catch (err: any) {
        spinner.fail(chalk.red(`Export failed: ${err.message}`));
        process.exit(1);
      }
      return;
    }

    if (!ADAPTERS[options.target]) {
      console.error(chalk.red(`Unknown adapter: ${options.target}`));
      console.log(chalk.gray(`Available: ${Object.keys(ADAPTERS).join(', ')}, agents-md`));
      process.exit(1);
    }

    const spinner = ora(`Exporting to ${ADAPTERS[options.target]} format...`).start();

    try {
      // Dynamically load the adapter
      const adapterModule = await loadAdapter(options.target);
      const adapter = new adapterModule();

      const outDir = options.out;
      mkdirSync(outDir, { recursive: true });

      await adapter.export(tastekitDir, outDir, {
        includeSkills: true,
        includePlaybooks: true,
      });

      spinner.succeed(chalk.green(`Exported to ${outDir}/`));
      console.log(chalk.cyan(`\nTarget: ${ADAPTERS[options.target]}`));
      console.log(chalk.gray(`Files written to: ${outDir}/`));
    } catch (err: any) {
      spinner.fail(chalk.red(`Export failed: ${err.message}`));
      process.exit(1);
    }
  });

async function loadAdapter(target: string): Promise<any> {
  switch (target) {
    case 'claude-code': {
      const mod = await import('../../../../adapters/claude-code/index.js');
      return mod.ClaudeCodeAdapter;
    }
    case 'manus': {
      const mod = await import('../../../../adapters/manus/index.js');
      return mod.ManusAdapter;
    }
    case 'openclaw': {
      const mod = await import('../../../../adapters/openclaw/index.js');
      return mod.OpenClawAdapter;
    }
    case 'autopilots': {
      const mod = await import('../../../../adapters/autopilots/index.js');
      return mod.AutopilotsAdapter;
    }
    default:
      throw new Error(`Unknown adapter: ${target}`);
  }
}

function generateAgentsMd(constitution: any, tastekitDir: string): string {
  const lines: string[] = [];

  lines.push('# AGENTS.md');
  lines.push('');
  lines.push('> Generated by TasteKit. Do not edit manually.');
  lines.push('');

  // Principles
  if (constitution.principles?.length > 0) {
    lines.push('## Principles');
    lines.push('');
    for (const p of constitution.principles) {
      lines.push(`- **${p.id}**: ${p.statement}`);
    }
    lines.push('');
  }

  // Tone
  if (constitution.tone) {
    lines.push('## Tone & Voice');
    lines.push('');
    if (constitution.tone.voice_keywords?.length > 0) {
      lines.push(`Voice: ${constitution.tone.voice_keywords.join(', ')}`);
    }
    if (constitution.tone.forbidden_phrases?.length > 0) {
      lines.push('');
      lines.push('**Avoid these phrases:**');
      for (const phrase of constitution.tone.forbidden_phrases) {
        lines.push(`- "${phrase}"`);
      }
    }
    lines.push('');
  }

  // Tradeoffs
  if (constitution.tradeoffs) {
    lines.push('## Behavior');
    lines.push('');
    if (constitution.tradeoffs.autonomy_level) {
      lines.push(`Autonomy level: ${constitution.tradeoffs.autonomy_level}`);
    }
    lines.push('');
  }

  // Taboos
  if (constitution.taboos?.length > 0) {
    lines.push('## Restrictions');
    lines.push('');
    for (const taboo of constitution.taboos) {
      lines.push(`- ${taboo}`);
    }
    lines.push('');
  }

  // Skills reference
  const skillsManifestPath = join(tastekitDir, 'skills', 'manifest.v1.yaml');
  if (existsSync(skillsManifestPath)) {
    lines.push('## Skills');
    lines.push('');
    lines.push('See `.tastekit/skills/` for available skills with progressive disclosure.');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${constitution.generator_version || '0.5.0'} on ${new Date().toISOString().split('T')[0]}*`);

  return lines.join('\n');
}
