/**
 * Autopilots Adapter
 * 
 * Reference adapter for Autopilots (community/optional).
 */

import { TasteKitAdapter, ExportOpts, InstallOpts } from '../adapter-interface.js';
import { readFileSync, writeFileSync, existsSync, cpSync } from 'fs';
import { join } from 'path';
import { resolveArtifactPath } from '@tastekit/core/utils/filesystem.js';

export class AutopilotsAdapter implements TasteKitAdapter {
  id = 'autopilots';
  version = '1.0.0';
  
  async detect(target: string): Promise<boolean> {
    return existsSync(join(target, 'autopilots.yaml'));
  }
  
  async export(profilePath: string, outDir: string, opts: ExportOpts): Promise<void> {
    // Supports both v1 flat and v2 three-space layouts
    const constitutionPath = resolveArtifactPath(profilePath, 'constitution');

    if (!existsSync(constitutionPath)) {
      throw new Error('Constitution not found. Run tastekit compile first.');
    }
    
    const constitution = JSON.parse(readFileSync(constitutionPath, 'utf-8'));
    
    // Generate Autopilots YAML
    const yaml = this.generateAutopilotsYAML(constitution);
    
    writeFileSync(join(outDir, 'autopilots.yaml'), yaml);
  }
  
  async install(outDir: string, target: string, opts: InstallOpts): Promise<void> {
    // Simple copy
    cpSync(outDir, target, { recursive: true });
  }
  
  private generateAutopilotsYAML(constitution: any): string {
    // Generate YAML format for Autopilots
    return `# Autopilots Configuration (Generated by TasteKit)

principles:
${constitution.principles.map((p: any) => `  - id: ${p.id}
    statement: ${p.statement}
    priority: ${p.priority}`).join('\n')}

tone:
  voice_keywords: [${constitution.tone.voice_keywords.map((k: string) => `"${k}"`).join(', ')}]
  forbidden_phrases: [${constitution.tone.forbidden_phrases.map((p: string) => `"${p}"`).join(', ')}]

tradeoffs:
  accuracy_vs_speed: ${constitution.tradeoffs.accuracy_vs_speed}
  autonomy_level: ${constitution.tradeoffs.autonomy_level}
`;
  }
}
